apiVersion: platform.helmsman.dev/v1alpha1
kind: AppDeployment
metadata:
  labels:
    app.kubernetes.io/name: helmsman-operator
    app.kubernetes.io/managed-by: kustomize
  name: appdeployment-sample
spec:
  # TODO(user): Add fields here
